# vercel.toml

# Specify the version of the Vercel configuration
version = 2

# Build settings
builds = [
  { src = "package.json", use = "@vercel/static-build" }
]

# Define the output directory after the build
outputDirectory = "dist"

# Define the routes for your application
routes = [
  { src = "/(.*)", dest = "/index.html" }
]

# Specify the environment variables (optional)
[env]
  NODE_ENV = "production"

# Optional: Configure a region
[regions]
  us = "1" # Specify a region (like '1' for US)
