# vercel.toml

version = 2

# Build settings
builds = [
  { src = "package.json", use = "@vercel/static-build" }
]

# Output directory after build
outputDirectory = "dist"

# Define the routes for your application
routes = [
  { src = "/(.*)", dest = "/index.html" }
]

# Optional: Configure environment variables
[env]
  NODE_ENV = "production"

